#!/bin/bash -eu

infile=${1:-testing/Testing.hs}

if [ ! -e $infile ]; then
  echo "File $infile does not exist."
  exit 1
fi
base="$(basename $infile)"
filename="${base%.*}"

cfile="$filename.c"
bin="$filename"

p=$(cabal exec printenv GHC_PACKAGE_PATH)

GHC_PACKAGE_PATH="$p" runhaskell "$infile"

#succes=0
#(
#echo '#include "util.h"'
#GHC_PACKAGE_PATH="$p" runhaskell "$infile"
#succes=$?
#) | tee "testing/$cfile"
#
#if [ $succes -eq 0 ]; then
#  pushd testing 1> /dev/null
#  gcc -g -Wall -o "$bin" "$cfile"
#  ./$bin
#  popd 1> /dev/null
#fi
