//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//
// Further modified by Sukhman Kahlon.
//
// On Thu Aug 14 14:52:29 PDT 2025
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTop(CLK,
             RST_N,
             sw,
             leds);
  input  CLK;
  input  RST_N;
  input [3:0] sw;
  output [3:0] leds;

  assign leds[3:0] = ifc_led_reg[3:0];

  // register ifc_led_reg
  reg [7 : 0] ifc_led_reg;
  wire [7 : 0] ifc_led_reg$D_IN;
  wire ifc_led_reg$EN;

  // register ifc_led_reg
  assign ifc_led_reg$D_IN = sw[3:0];
  assign ifc_led_reg$EN = 1'd1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        ifc_led_reg <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (ifc_led_reg$EN)
          ifc_led_reg <= `BSV_ASSIGNMENT_DELAY ifc_led_reg$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    ifc_led_reg = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTop
